# Generated by Django 4.0.1 on 2022-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarant',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
